# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
#
# Recreate secrets.yml

development:
  secret_key_base: fc4e5a956e1a5bbfcb7e34d103d864ac0cb14acf33fe41abb64a466376f679dc4f189357b8c4e0ae4aef2fba9ddb43b4624d3b14b7707ef926cdef0a350085ee
  google_client_id: 726045945389-aed9gr5eeil7ni3n0d397r3jq48kscvk.apps.googleusercontent.com
  google_client_secret: Ug36ATTLiTVRJVDt-y67AitD
test:
  secret_key_base: 351fd563860ccb7f4941047088f7a273d0ad6f1d2ee2f16e925326d0a8c957ce15b5db6c527fdad081b95a836e437a98ba325388088445ba2d7b1b3a0fadb7d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
